apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: domain-tracker

resources:
  - namespace.yaml
  - pvc.yaml
  - secret.yaml
  - deployment.yaml
  - service.yaml

images:
  - name: 192.168.4.162:5000/domain-expiry-tracker
    newTag: latest
