apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: domain-tracker

resources:
  - namespace.yaml
  - pvc.yaml
  - secret.yaml
  - deployment.yaml
  - service.yaml
  - route.yaml

images:
  - name: domain-expiry-tracker
    newName: ghcr.io/michaeldigiacomi/domain-expiry-tracker
    newTag: latest
