apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: domain-tracker-route
  namespace: domain-tracker
spec:
  parentRefs:
    - name: main-gateway
      namespace: default
  hostnames:
    - "domains.digitaladrenalin.net"
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: domain-tracker
          namespace: domain-tracker
          port: 80
